apiVersion: v1
kind: Service
metadata:
  name: reducers
  namespace: mapreduce
  labels:
    app: reducers
spec:
  ports:
  - port: 8082
  clusterIP: None
  selector:
    app: reducers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: reducer
  namespace: mapreduce
spec:
  serviceName: "reducers"
  replicas: 3
  selector:
    matchLabels:
      app: reducers
  template:
    metadata:
      labels:
        app: reducers
    spec:
      containers:
      - name: mapreduce-reducer
        image: mapreduce-reducer:latest
        ports:
        - containerPort: 8082
        imagePullPolicy: Never
  updateStrategy:
    type: OnDelete