kind: Service
apiVersion: v1
metadata:
  name: mapreduce-master
  namespace: mapreduce
spec:
  selector:
    app: mapreduce-master
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: mapreduce-master
  namespace: mapreduce
  labels:
    app: mapreduce-master
spec:
  containers:
  - name: mapreduce-master
    image: mapreduce-master:latest
    ports:
    - containerPort: 8080
    env:
    - name: MAPPER_HOST
      value: "mappers"
    - name: REDUCER_HOST
      value: "reducers"
    - name: MAPPER_PORT
      value: "8081"
    - name: REDUCER_PORT
      value: "8082"
    imagePullPolicy: Never