apiVersion: v1
kind: Service
metadata:
  name: mappers
  namespace: mapreduce
  labels:
    app: mappers
spec:
  ports:
  - port: 8081
  clusterIP: None
  selector:
    app: mappers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapper
  namespace: mapreduce
spec:
  serviceName: "mappers"
  replicas: 3
  selector:
    matchLabels:
      app: mappers
  template:
    metadata:
      labels:
        app: mappers
    spec:
      containers:
      - name: mapreduce-mapper
        image: mapreduce-mapper:latest
        ports:
        - containerPort: 8081
        imagePullPolicy: Never
  updateStrategy:
    type: OnDelete